---
name: Checks

# trigger
on: [push]

jobs:
  # define a job, named test-lint
  test-lint:
    name : Test and Lint
    runs-on: ubuntu-24.04

    steps:
      # Log into Docker Hub: Xác thực để tránh bị giới hạn rate limit khi pull image.
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Checkout code: Lấy code về runner để chuẩn bị kiểm tra.
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      # Run Tests: Đảm bảo test chỉ chạy khi DB sẵn sàng.
      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Run Linter: Chạy kiểm tra style code với flake8.
      - name: Run Linter
        run: docker-compose run --rm app sh -c "flake8"